---
title: "Quick start"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    highlight: "textmate"
    css: "custom.css"
# bibliography: "example.bib"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Quick start}
---

```{r, message=FALSE}
library(gsdcut)
library(tibble)
library(simtrial)
```

# Simulate TTE data
```{r}
set.seed(123)
my_tte <- simPWSurv(
   n = 800,
   strata = tibble(Stratum = c("Positive", "Negative"),
                   p = c(.5, .5)),
   failRates = tibble(Stratum = rep(c("Positive","Negative"), 2),
                      period = rep(1, 4),
                      Treatment = c(rep("Control", 2), rep("Experimental", 2)),
                      duration = rep(1, 4),
                      rate = log(2) / c(6, 9, 9, 12)),
   dropoutRates = tibble(Stratum = rep(c("Positive", "Negative"),2),
                         period = rep(1, 4),
                         Treatment = c(rep("Control", 2), rep("Experimental", 2)),
                         duration = rep(1, 4),
                         rate = rep(.001, 4)))
```

# Build R6 class for `Cut`
```{r}
# cut by targeted events
cut1 <- gsdcut::Cut$new(event = 100)
cut1 |> summary()

# cut by planned duration
cut2 <- gsdcut::Cut$new(time = 16)
cut2 |> summary()

# cut by minimal follow-up
cut3 <- gsdcut::Cut$new(min_followup = 12)
cut3 |> summary()

# cut by max of planned duration, targeted events
cut4 <- gsdcut::Cut$new(time = 12, event = 100)
cut4 |> summary()

# cut by max of minimum follow-up, targeted events
cut5 <- gsdcut::Cut$new(min_followup = 13, event = 100)
cut5 |> summary()
```

# Get cut dates
```{r}
# cut by targeted events
my_tte |> get_cut_date(cut_class = cut1)

# cut by planned duration
my_tte |> get_cut_date(cut_class = cut2)

# cut by minimal follow-up
# my_tte |> get_cut_date(cut_class = cut1)

# cut by max of planned duration, targeted events
my_tte |> get_cut_date(cut_class = cut4)

# cut by max of minimum follow-up, targeted events
# my_tte |> get_cut_date(cut_class = cut5)
```




# References
